import { GamePreset } from '../types';

export const PRESETS: GamePreset[] = [
  {
    id: 'developer-brief-sample',
    name: 'Developer Brief Demo (6 from 1..15)',
    description: 'Exact 3 >= 1, Exact 2 >= 3 guarantee wheel for fast interactive demonstration.',
    from: 1,
    to: 15,
    ticketSize: 6,
    resultSize: 6,
    targets: { 3: 1, 2: 3 },
  },
  {
    id: 'compact-pick6-3if3',
    name: 'Pick 6 Compact (6 from 1..12)',
    description: 'Guarantees at least one Exact 3 match for any 6-number draw.',
    from: 1,
    to: 12,
    ticketSize: 6,
    resultSize: 6,
    targets: { 3: 1 },
  },
  {
    id: 'compact-pick6-4if6',
    name: 'Pick 6 Exact 4 Guarantee (6 from 1..14)',
    description: 'Ensures at least one ticket has Exact 4 matches with any draw.',
    from: 1,
    to: 14,
    ticketSize: 6,
    resultSize: 6,
    targets: { 4: 1 },
  },
  {
    id: 'pick5-wheel',
    name: 'Pick 5 Guarantee (5 from 1..15)',
    description: 'Guarantees at least one Exact 3 match for any 5-number draw.',
    from: 1,
    to: 15,
    ticketSize: 5,
    resultSize: 5,
    targets: { 3: 1 },
  },
  {
    id: 'mini-lotto-high-exact',
    name: 'Balanced Dual Target (6 from 1..13)',
    description: 'Exact 3 >= 2 and Exact 2 >= 8 for balanced prize coverage.',
    from: 1,
    to: 13,
    ticketSize: 6,
    resultSize: 6,
    targets: { 3: 2, 2: 8 },
  },
  {
    id: 'zero-index-range',
    name: '0-Indexed System (5 from 0..12)',
    description: 'Demonstrating 0-based range support (from 0 to 12).',
    from: 0,
    to: 12,
    ticketSize: 5,
    resultSize: 5,
    targets: { 3: 1 },
  },
];
